#include "lcd.h"
#include "buttons.h"
#include "snake.h"


typedef enum{ BUT1 = 1, BUT2 = 2} ButtonType;
static uint8_t PAUSE = 1; //0 -> PAUSE, 1 -> start

/*Number of IRQ generated by PORTC_PORTD interrupt*/
static const IRQn_Type myPORT_IRQn =  31;  	/* Define interrupt (IRQ) number for PORTB. Check MKL05Z4 or find in NVIC section of KL05 Sub-Family Reference Manual - NVIC section */ 


void PORTB_IRQHandler(void)									/* Put a proper name of PORTB Interrupt service routine ISR. See system_MKL05Z4.s file for function name */ 
{
	//reset button
	if( PORTB->ISFR & (1 << BUT1) ){          /* Check in ISFR register if button BUT1 is pressed */
		reset_game();
		snake_init();
    while((FPTB->PDIR&(1<<BUT1))==0);				/* Enable wait in the interrupt for SW1 button release */	
		PORTB->PCR[BUT1] |= (1<<24);					  /* Make sure that interrupt service flag (ISF) in Port Control Register is cleared during ISR execution */
  }
	
	if( PORTB->ISFR & (1 << BUT2) ){     
		if(PAUSE)
		{
				//pause
				set_pause(0);
		}
		else 
		{
				//start
				set_pause(1);

		}
    while((FPTB->PDIR&(1<<BUT2))==0);				
		PORTB->PCR[BUT2] |= (1<<24); 

  }
	scoreboard();
}

//getter
uint8_t get_pause()
{
	return PAUSE;
}

//setter
void set_pause(uint8_t p)
{
	PAUSE = p;
}


void buttonsInitialize(void){
	SIM->SCGC5 |=  SIM_SCGC5_PORTB_MASK; 				/* Enable clock for port B */
	PORTB->PCR[BUT1] |= PORT_PCR_MUX(1);      	/* Pin PTB0 is GPIO */
	PORTB->PCR[BUT2] |= PORT_PCR_MUX(1);      	/* Pin PTB1 is GPIO */
	
	/* Port control register for bit 3 of port C configuration. Activate pull up and interrupt */
	PORTB->PCR[BUT1] |= (1<<1);			/* Set PE bit in PCR register to enable pull resistor. See KL05 Sub-Family Reference Manual */
	PORTB->PCR[BUT1] |= (1<<0);			/* Set PS bit in PCR register to select pull up. See KL05 Sub-Family Reference Manual */
	PORTB->PCR[BUT1] |= (1<<19);		/* Set value for IRQC bit field in PCR register to select rising edge interrupts for PORTB. See KL05 Sub-Family Reference Manual */
	PORTB->PCR[BUT1] |= (0<<18);
	PORTB->PCR[BUT1] |= (1<<17);
	PORTB->PCR[BUT1] |= (0<<16);
	PORTB->PCR[BUT2] |= (1<<1);			/* Set PE bit in PCR register to enable pull resistor. See KL05 Sub-Family Reference Manual */
	PORTB->PCR[BUT2] |= (1<<0);			/* Set PS bit in PCR register to select pull up. See KL405 Sub-Family Reference Manual */
	PORTB->PCR[BUT2] |= (1<<19);	  /* Set value for IRQC bit field in PCR register to select falling edge interrupts for PORTB. See KL05 Sub-Family Reference Manual */
	PORTB->PCR[BUT2] |= (0<<18);
	PORTB->PCR[BUT2] |= (1<<17);
	PORTB->PCR[BUT2] |= (0<<16);
	
		
	/* ARM's Nested Vector Interrupt Controller configuration */
	NVIC_ClearPendingIRQ(myPORT_IRQn);				/* Clear NVIC any pending interrupts on PORTC_B */
	NVIC_EnableIRQ(myPORT_IRQn);							/* Enable NVIC interrupts source for PORTC_B module */
	NVIC_SetPriority (myPORT_IRQn, 3);				/* Set POR_B interrupt priority level  */ 
}


